# Generated by Django 3.1.7 on 2021-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meususer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('idade', models.IntegerField(blank=True, null=True, verbose_name='Sua idade')),
                ('curso', models.CharField(choices=[('CC', 'CC'), ('SPI', 'SPI'), ('ADS', 'ADS')], default='CC', max_length=20, verbose_name='Curso')),
                ('periodo', models.IntegerField(blank=True, null=True, verbose_name='Seu período')),
            ],
        ),
    ]
